# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import datetime
from db_controller import Controller


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(289, 331)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.login = QtWidgets.QLineEdit(self.centralwidget)
        self.login.setInputMask("")
        self.login.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.login.setObjectName("login")
        self.verticalLayout.addWidget(self.login)

        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setInputMask("")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText('Неверный логин или пароль')
        self.label.setVisible(False)
        self.verticalLayout.addWidget(self.label)

        self.cBox_pRem = QtWidgets.QCheckBox(self.centralwidget)
        self.cBox_pRem.setChecked(False)
        self.cBox_pRem.setObjectName("cBox_pRem")
        self.verticalLayout.addWidget(self.cBox_pRem)

        self.cBox_pShow = QtWidgets.QCheckBox(self.centralwidget)
        self.cBox_pShow.setEnabled(True)
        self.cBox_pShow.setChecked(False)
        self.cBox_pShow.setObjectName("cBox_pShow")
        self.cBox_pShow.clicked.connect(self.showPassword)
        self.verticalLayout.addWidget(self.cBox_pShow)

        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout.addWidget(self.loginButton)

        self.regButton = QtWidgets.QPushButton(self.centralwidget)
        self.regButton.setObjectName("regButton")
        self.verticalLayout.addWidget(self.regButton)

        self.forgButton = QtWidgets.QPushButton(self.centralwidget)
        self.forgButton.setObjectName("forgButton")
        self.verticalLayout.addWidget(self.forgButton)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 289, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login.setPlaceholderText(_translate("MainWindow", "Имя пользователя"))
        self.password.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.cBox_pRem.setText(_translate("MainWindow", "Запомнить меня"))
        self.cBox_pShow.setText(_translate("MainWindow", "Показать пароль"))
        self.loginButton.setText(_translate("MainWindow", "Войти"))
        self.regButton.setText(_translate("MainWindow", "Регистрация"))
        self.forgButton.setText(_translate("MainWindow", "Забыли пароль?"))

    def showPassword(self):
        if self.cBox_pShow.isChecked():
            self.password.setEchoMode(QtWidgets.QLineEdit.Normal)
        else:
            self.password.setEchoMode(QtWidgets.QLineEdit.Password)


class RegistrationDialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super(RegistrationDialog, self).__init__(parent)

        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")

        self.login = QtWidgets.QLineEdit()
        self.login.setInputMask("")
        self.login.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.login.setObjectName("email")
        self.login.setPlaceholderText('Введите логин')
        self.verticalLayout.addWidget(self.login)

        self.password = QtWidgets.QLineEdit()
        self.password.setInputMask("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.password.setPlaceholderText('Введите пароль')
        self.verticalLayout.addWidget(self.password)

        self.password_repeat = QtWidgets.QLineEdit()
        self.password_repeat.setInputMask("")
        self.password_repeat.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_repeat.setObjectName("password_repeat")
        self.password_repeat.setPlaceholderText('Повторите пароль')
        self.verticalLayout.addWidget(self.password_repeat)

        self.label = QtWidgets.QLabel("Дата рождения:")
        self.date = QtWidgets.QDateEdit()
        self.date.setObjectName("date")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.date)

        self.acceptButton = QtWidgets.QPushButton(self)
        self.acceptButton.setObjectName("acceptButton")
        self.acceptButton.clicked.connect(self.createUser)
        self.acceptButton.setText("Ок")
        self.verticalLayout.addWidget(self.acceptButton)

        self.cancleButton = QtWidgets.QPushButton(self)
        self.cancleButton.setObjectName("cancleButton")
        self.cancleButton.clicked.connect(self.closeDialog)
        self.cancleButton.setText("Отмена")
        self.verticalLayout.addWidget(self.cancleButton)

        self.setWindowTitle("Регистрация")
        self.setGeometry(QtCore.QRect(0, 0, 289, 30))

    def closeDialog(self):
        self.close()

    def createUser(self):
        self.login.setStyleSheet("background-color: None")
        self.login.update()
        self.password.setStyleSheet("background-color: None")
        self.password_repeat.setStyleSheet("background-color: None")
        self.password.update()
        self.password_repeat.update()
        try:
            datetime.datetime.strptime(self.date.text(), "%d %b %Y")
            if len(self.login.text()) == 0:
                self.label.setStyleSheet("background-color: Red")
                self.label.setText('Минимальная длина логина - 1 символ.')
                self.label.update()

            elif self.password.text() != self.password_repeat.text():
                self.label.setStyleSheet("background-color: Red")
                self.label.setText('Пароли не совпадают.')
                self.label.update()

            elif len(self.login.text()) > 0 and len(self.password.text()) > 0 and self.password.text() == self.password_repeat.text():
                date = self.date.text()
                login = self.login.text()
                password = self.password.text()
                date = datetime.datetime.strptime(date, "%d %b %Y")
                date = f"{date.year}-{date.month}-{date.day}"
                callback = Controller().sign_up(email=login, password=password, date=date)
                self.label.setStyleSheet("background-color: Green")
                self.label.setText('Пользователь создан')
                self.label.update()
        except Exception as exc:
            print(exc)
            if exc.code == 'gkpj':
                self.label.setText('Пользователь с таким логином уже существует')
                self.label.setStyleSheet("background-color: Red")
            else:
                self.label.setStyleSheet("background-color: Red")
                self.label.setText('Данные введены неверно.')
                self.label.update()


class RestorePasswordDialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super(RestorePasswordDialog, self).__init__(parent)

        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")

        self.login = QtWidgets.QLineEdit()
        self.login.setInputMask("")
        self.login.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.login.setObjectName("email")
        self.login.setPlaceholderText('Введите email')
        self.verticalLayout.addWidget(self.login)

        self.acceptButton = QtWidgets.QPushButton(self)
        self.acceptButton.setObjectName("acceptButton")
        self.acceptButton.clicked.connect(self.closeDialog)
        self.acceptButton.setText("Восстановить")
        self.verticalLayout.addWidget(self.acceptButton)

        self.cancleButton = QtWidgets.QPushButton(self)
        self.cancleButton.setObjectName("cancleButton")
        self.cancleButton.clicked.connect(self.closeDialog)
        self.cancleButton.setText("Отмена")
        self.verticalLayout.addWidget(self.cancleButton)

        self.setWindowTitle("Восстановление пароля")
        self.setGeometry(QtCore.QRect(0, 0, 289, 30))

    def closeDialog(self):
        self.close()
